FROM rdmix/alinode-base:v0.0.5

LABEL maintainer="starkwang wsd312@163.com"
LABEL name="alinode-base"
LABEL version="v0.0.1"
# echo env
RUN echo node $(node -v) \
    && npm -v \
    && yarn -v \
    && tnvm -v \
    && which node \
    && which pm2

ENTRYPOINT ["/bin/bash"]
