FROM rdmix/alinode-base:v0.0.11

LABEL maintainer="starkwang wsd312@163.com"
LABEL name="alinode-base"
LABEL version="v0.0.1"
# echo env 
RUN echo node `node -v` \
    && echo node `npm -v` \
    && echo node `yarn -v` \
    && echo node `tnvm -v` \
    && which node \
    && which agenthub \
    && which pm2

ENTRYPOINT ["/bin/bash"]
